---
# tasks file for roles/nfs-share

- name: system packages | nfs server
  become: true
  ansible.builtin.dnf:
    update_cache: true
    name: nfs-utils
    state: present

- name: nfs server | configure shares
  become: true
  ansible.builtin.template:
    backup: true
    dest: /etc/exports
    src: exports.j2
    mode: 0644
  notify:
    - refresh nfs

- name: nfs server | enable nfs
  become: true
  ansible.builtin.service:
    enabled: true
    name: nfs-server
    state: started
