---
- hosts: all

  pre_tasks:

    - name: Create unprivileged test user
      ansible.builtin.user:
        name: test
        uid: 12345

    - name: Create directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: test
        mode: 0755
      with_items:
        - /srv/share
        - /mnt/rw

  roles:

    - role: ome.nfs_share
      nfs_shares:
        /srv:
          - host: "*"
            options: "rw,fsid=0"

    - role: nfs_mount
      nfs_share_mounts:
        - path: /mnt/rw
          location: localhost:/share
          opts: rw
